<?php 
/*
 *    Copyright (c) 2010 Just Another Video script
 *
 *    This file is part of Just Another Video script.
 *    Come to website for support or buying additional plugins/modules.
 *    http://justanothervideoscript.com/	
 */
include_once("adminfunctions.inc");
?>
<fieldset>
	<ol>
		<li>
				<h2>&nbsp;&nbsp;You can buy Server 2 Server for only 10euro</h2>
		</li>
		<li>
				<a href="http://justanothervideoscript.com/products/video-script/server-2-server/"><h2>Click Here to buy now</h2></a>
		</li>		
		
		
	</ol>
</fieldset>				
