<?php 
/*
 *    Copyright (c) 2010 Just Another Video script
 *
 *    This file is part of Just Another Video script.
 *    Come to website for support or buying additional plugins/modules.
 *    http://justanothervideoscript.com/	
 */
$mustbeeightteen = '<div id="home"><h2>18 USC 2257</h2><br />

<p>
'.getSetting(sitename, $db).' is not a producer (primary or secondary) of any and all of the content found on the website (Porncows.com). 
With respect to the records as per 18 USC 2257 for any and all content found on this site, please kindly direct your request to the site for which the content was produced. 
</p>
<p>
'.getSetting(sitename, $db).' is a video sharing site in which allows for the uploading, sharing and general viewing of various types of adult content and while Porncows.com does the best it can with verifying compliance, it may not be 100% accurate. 
</p>
<p>
'.getSetting(sitename, $db).' abides by the following procedures to ensure compliance: 
*  Requiring all users to be 18 years of age to upload videos.
*  When uploading, user must verify the content; assure he/she is 18 years of age; certify that he/she keeps records of the models in the content and that they are over 18 years of age.
*  Certify that the content being uploaded is either owned by the user or they are legally licensed to upload, publish, share the content at hand.
</p>
<p>
'.getSetting(sitetitle, $db).' allows content to be flagged as inappropriate. Should any content be flagged as illegal, unlawful, harassing, harmful, offensive or various other reasons, Porncows.com shall remove it from the site without delay.
</p>
<p>
'.getSetting(sitetitle, $db).'<br>
'.getSetting(contact_email, $db).'<br>
'.getSetting(sitetitle, $db).' online<br>
</p></div>' ;

?>