<?php 
/*
 *    Copyright (c) 2010 Just Another Video script
 *
 *    This file is part of Just Another Video script.
 *    Come to website for support or buying additional plugins/modules.
 *    http://justanothervideoscript.com/	
 */
$dmca = '<div id="home"><h2>DMCA Notice of Copyright Infringement</h2><br />

<p>
DMCA Notice of Copyright Infringement '.getSetting(sitetitle, $db).' Adult Video is an online service provider as defined in the Digital Millennium Copyright Act.
We provide legal copyright owners with the ability to self-publish on the Internet by uploading, storing and displaying various types of media.
We do not actively monitor, screen or otherwise review the media which is uploaded to our servers by users of the service. 
We take copyright violation very seriously and will vigorously protect the rights of legal copyright owners. 
If you are the copyright owner of content which appears on '.getSetting(sitename, $db).' website and you did not authorize the use of the content you must notify us in writing in order for us to identify the allegedly infringing content and take action.
</p>
<p>
Specific identification of the copyrighted work which you are alleging to have been infringed.
If you are alleging infringement of multiple copyrighted works with a single notification you must submit a representative list which specifically identifies each of the works that you allege are being infringed. 
Specific identification of the location and description of the material that is claimed to be infringing or to be the subject of infringing activity with enough detailed information to permit us to locate the material. 
You should include the specific URL or URLs of the webpages where the allegedly infringing material is located. 
Information reasonably sufficient to allow us to contact the complaining party which may include a name, address, telephone number and electronic mail address at which the complaining party may be contacted. 
</p>
<p>
A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law. 
A statement that the information in the notification is accurate, and under penalty of perjury that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
</p>
<p>
Written notice should be sent to our designated agent as follows:
<br>
Bottom line if there is something of yours on my site I will be happy to remove it.
<br>
DMCA AGENT<br>
Porncows website<br>
Email: '.getSetting(contact_email, $db).'<br>
<br>
Please also note that under applicable law, 17 U.S.C. 512 (f), any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability. 
</p></div>' ;

?>